### PR TITLE
github: Add action and PR template

### PR DESCRIPTION
**Pull request by netoax**
**Describe what this PR introduces:** 

This PR adds a github action to automate NPM library publication when a new release is created.

related to #20 

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bug fix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [X] Other, please describe: Github

**Does this PR introduce any breaking changes?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] Related issues are referenced in the PR (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included

**Testing environment:**

- Operating System/Platform: macOS Darwin - 18.0.0
- Node version: v12.16.2
- Yarn version: 1.16.0

### CODE REVIEW

**Review by lcbm — APPROVED** [review]
:100:

**Review by ramonhpr — APPROVED** [review]
Nice!
Just a suggestion for future work on actions.
There is a github actions guide for node [here](https://help.github.com/pt/actions/language-and-framework-guides/using-nodejs-with-github-actions) ?
There, you can find concepts like using cache (to install npm packages just when the package.lock has changed), or using `npm ci` and OS platform build.
maybe the project can use one of these concepts :smile:

**Comment by lcbm** [comment]
> Nice!
> Just a suggestion for future work on actions.
> There is a github actions guide for node [here](https://help.github.com/pt/actions/language-and-framework-guides/using-nodejs-with-github-actions) ?
> There, you can find concepts like using cache (to install npm packages just when the package.lock has changed), or using `npm ci` and OS platform build.
> maybe the project can use one of these concepts

@ramonhpr, I opened an issue #20 with your suggestion, in a way that it even if we don't have time to test it this sprint, it's registered as an issue and we can later improve our workflow base on your insights! If @netoax adopts these changes, then we can close it for this repo but then replicate it for the other ones :wink: 

Thanks for helping us with tests, it's crucial for us :heart:

**Review by esdrasjnr — APPROVED** [review]
LGTM! :+1:

**Comment by netoax** [comment]
> Nice!
> Just a suggestion for future work on actions.
> There is a github actions guide for node [here](https://help.github.com/pt/actions/language-and-framework-guides/using-nodejs-with-github-actions) ?
> There, you can find concepts like using cache (to install npm packages just when the package.lock has changed), or using `npm ci` and OS platform build.
> maybe the project can use one of these concepts 😄

Thanks for the suggestion, man. I probably won't investigate it this sprint but as @lcbm created the issue, I will come back to this later.

**Pull request merged**
